---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rainloop.fullname" . }}
  labels:
    {{- include "std.labels" . | indent 2 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rainloop.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "std.labels" . | indent 6 }}
    spec:
      volumes:
        - name: fpm-run-volume
          emptyDir:
            medium: Memory
            sizeLimit: 1M
        - name: rainloop-app-config
          configMap:
            name: {{ template "rainloop.fullname" . }}-app-cfg
        - name: rainloop-domains-config
          configMap:
            name: {{ template "rainloop.fullname" . }}-domains
      containers:
        - name: {{ template "rainloop.name" . }}-backend
          image: "{{ .Values.image.repository }}/rainloop-backend:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # TODO: check and implement readiness and liveness probe
          readinessProbe:
            exec:
              command:
                - /bin/ls
                - /var/run/php/php7.0-fpm.sock
          volumeMounts:
            - mountPath: /var/run/php
              name: fpm-run-volume
            - mountPath: /var/www/rainloop/data/_data_/_default_/configs
              name: rainloop-app-config
              readOnly: true
            - mountPath: /var/www/rainloop/data/_data_/_default_/domains
              name: rainloop-domains-config
              readOnly: true
        - name: {{ template "rainloop.name" . }}-frontend
          image: "{{ .Values.image.repository }}/rainloop-frontend:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # TODO: implement liveness and readiness probe
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - mountPath: /var/run/php
              name: fpm-run-volume
