apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "rainloop.fullname" . }}-storage-claim
  labels:
    {{- include "std.labels" . | indent 4 }}
spec:
  storageClassName: {{ if .Values.pvClaim }}{{ default "" .Values.pvClaim.storageClassName | quote }}{{ end }}
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 100Mi
