---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rainloop.fullname" . }}-salt-secret
  labels:
    {{- include "std.labels" . | indent 2 }}
type: Opaque
data:
  SALT.php: {{ cat "<?php //" (default (randAlphaNum 128) .Values.passwordSalt) | b64enc }}
