apiVersion: v1
kind: Service
metadata:
  name: {{ template "rainloop.fullname" . }}-service
  labels:
    {{- include "std.labels" . | indent 2 }}
spec:
  {{- if (.Values.service) and .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    {{- if .Values.service }}
    - port: {{ default 80 .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    app: {{ template "rainloop.name" . }}
    release: {{ .Release.Name }}
  sessionAffinity: {{ if .Values.service }}{{ default "ClientIP" .Values.service.sessionAffinity }}{{ end }}
