apiVersion: v1
kind: Service
metadata:
  labels:
    app: rainloop
    release: 0.1.0
  name: rainloop
spec:
  clusterIP: 10.108.105.120
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rainloop
    release: 0.1.0
  type: ClusterIP

