apiVersion: v1
kind: Service
metadata:
  name: {{ template "rainloop.fullname" . }}-service
  {{- template "std.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "rainloop.name" . }}
    release: {{ .Release.Name }}
